const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const packagePath = path.join(root, "package.json");
const outputPath = path.join(root, "src", "shared", "config", "game-version.ts");

const pkg = JSON.parse(fs.readFileSync(packagePath, "utf8"));
const version = String(pkg.version ?? "0.0.0");

if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
	throw new Error(`package.json version must be semantic versioning. Got: ${version}`);
}

const contents = `// Generated by scripts/sync-version.js from package.json. Do not edit by hand.
export const GAME_VERSION = "${version}";
export const GAME_VERSION_LABEL = "v" + GAME_VERSION;
`;

fs.writeFileSync(outputPath, contents);
console.log(`Synced game version ${version} -> ${path.relative(root, outputPath)}`);
